### PR TITLE
[DRAFT] Add PAM module for smack

### PR DESCRIPTION
**Pull request by jobol**
This is a draft for review

There are currently some existing PAM module for Smack:
 - in tizen
 - in smack-util (from github)

But there is no official places for some PAM module for Smack. For this reason I think that here is the good place.

The module I propose can behave like the module of tizen if invoked as below:
```
session optional pam_smack.so =User
```

### CODE REVIEW

**Comment by cschaufler** [comment]
I am on leave for the next couple weeks. I will review this when I return. Thank you for creating this.

**Comment by jobol** [comment]
cool, it let's me time to add installation of man page

**Comment by cschaufler** [comment]
I don't see a mechanism for an administrator to specify labels for individual users. For example, Fred is logged in with Smack label User::Fred, Betty gets User::Betty. Is this the intention?

**Comment by jobol** [comment]
There is one: If you put on the calling line of the PAM file a list of identities and labels. To be clear, you can write a line like:
```
session  optional  pam_smack.so root=System Fred=User::Fred Betty=User::Betty =User
```
But it is not ansewring your concern. There is a need for some templating like:
```
session  optional  pam_smack.so root=System  =User::%i
```
Where `%i` is the name of the user.

**Comment by jobol** [comment]
But introducing templating might have consequences on the rule set of the SMACK system. Example: how to tell that each user context labelled `User::%i` has read access to resource labelled `Foo`?

**Comment by cschaufler** [comment]
I'm not sure I understand the question.
% grep "^User::jobol Foo" /sys/fs/smackfs/load2
will show you what access, if any, Jobol has to objects labeled Foo.

**Comment by jobol** [comment]
What I wanted to point out is that if Smack runs on a multi user computer, then there is probably something to do somewhere.
By hypothesis, I'm getting your proposal: the PAM module can add the login name to Smack's context (ie. User:jobol), possibly by implementing some pattern substitution (ie. User:%i).
Then, let suppose there is a daemon that runs with Smack's context DAEMON and that must access to files having users's Smack's context.
To do so you have to add a set of rules for each user known by the system. One can argue that its gives full access control. But an other could also argue that some daemon must be always granted for such access in any case.
The trouble comes from the latter case because there is no way to express a generic rule telling that DAEMON has acess to any file labelled User:XXX where XXX doesn't care.
That was what I wanted to point out. I hope it is clearer now.

But troubles also comes from any case because there is a need to create set of rules when adding user or when adding programs holding own Smack's running context.

**Comment by cschaufler** [comment]
Good point on access to daemon services. That make User::jobol difficult to address. With that in mind I think your original proposal is worthy of moving forward.

**Comment by jobol** [comment]
Hi Casey, is there a chance that proposal comes in?

**Comment by jobol** [comment]
ping @cschaufler

**Comment by cschaufler** [comment]
On 5/22/2023 8:41 AM, jobol wrote:
>
> ping @cschaufler <https://github.com/cschaufler>
>
As no one has commented on the request I have pulled it.
Thank you.

**Comment by jobol** [comment]
\o/

While reading the discussion, I though that providing substitution will not break compatibility and can be valuable. So will propose that evolution later when I get time to do so.

**Pull request merged**
